### ISSUE TITLE
How to run the examples?

### ISSUE THREAD

**Issue by bartonhammond** [bitbldr/sprocket_docs#4]
I have the project running and I can see there are a lot of examples in the `src\components` - how can they be run?  For example, `products.gleam`

**Comment by eliknebel** [comment]
I would recommend starting out with https://github.com/bitbldr/sprocket_starter and if there are components you would like to try out from the docs, pulling those files into that project. From there it is just a matter of importing the component and rendering in a view. The main page is probably the best place to start `src/app/components/page.gleam`. In that file you can see how some of the example components are being imported and render but the gist of it would be:

1. Copy the products module file (or any of the other example component modules) from sprocket_docs e.g. https://github.com/bitbldr/sprocket_docs/blob/master/src/docs/components/products.gleam into your starter project `src/app/components/products.gleam`

2. In `src/app/components/page.gleam` import the component into the module
```gleam
import app/components/products.{ProductListProps, product_list, example_products}
```

3. Somewhere in the view, render the component
```gleam
component(
  product_list,
  ProductListProps(products: example_products()),
)
```

4. To actually run the project, use `yarn watch`. (you might need to install [watchexec](https://github.com/watchexec/watchexec) to watch for changes. If you dont want to use watchexec, you can always just build the assets manually and use `gleam run`)
```bash
yarn build && gleam run
```

**Comment by bartonhammond** [comment]
@eliknebel Thanks!
